
[workspace]
resolver = '2'
members = [
	'apps/lazynx',
	'libs/shared/config',
	'libs/shared/tui',
	'libs/status',
	'libs/shared/common',
	'libs/shell',
	'libs/shared/events',
	'libs/shared/logger',
	'libs/shared/errors',
	'libs/shared/actions',
]

[profile.release]
lto = true
