
[workspace]
resolver = '2'
members = [
	'apps/lazynx',
	'libs/shared/logger',
	'libs/shared/tui',
	'libs/shared/errors',
	'libs/shared/common',
	'libs/shared/config',
]

[profile.release]
lto = true
