[package]
name = "lazynx"
version = "0.1.0"
edition = "2021"


[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
tokio = { version = "1.41.0", features = ["full"] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
