[package]
name = "lazynx"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.93"
crossterm = "0.28.1"
log = "0.4.22"
ratatui = "0.29.0"
scopeguard = "1.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
