name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: read

jobs:
  main:
    name: CI Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Start Nx Cloud
        run: bunx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - name: Install Dependencies
        run: bun install --no-cache

      - name: Set SHAs for Nx Affected
        uses: nrwl/nx-set-shas@v4

      - name: Build, Test, and Lint Affected Changes
        run: bun nx affected -t lint test build
